language: c++

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsfml-dev cmake stockfish
  - sudo apt-get install -qq cppcheck

script:
  - cppcheck --error-exitcode=1 src/
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests
